version: '3.9'

services:
  server:
    build: .
    ports:
      - '4004:4004'
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'linexc'
      POSTGRES_USER: 'tuser'
      POSTGRES_DB: 'user'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
